---
# tasks file for ./roles/mysql
- name: Installing mysql On Ubuntu
  apt: 
    name: 
      - mariadb-server
      - python3-mysqldb
    state: latest
    update_cache: yes
  become: yes
  when: ansible_os_family == "Debian"
  notify: Starting Service

- name: Installing mysql On REHL
  dnf:
    name:
     - mariadb-server
     - python3-PyMySQL
    state: latest
    update_cache: yes
  become: yes
  when: ansible_os_family == "RedHat"
  notify: Starting Service

